name: Build and Package

on:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Verify Go version
      run: go version

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o dashball ./src

    - name: Archive the build output
      run: |
        tar czf dashball-linux.tar.gz dashball

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output-linux
        path: |
          dashball
          dashball-linux.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Verify Go version
      run: go version
      shell: pwsh

    - name: Build for Windows
      run: |
        $env:GOOS = "windows"
        $env:GOARCH = "amd64"
        go build -o dashball.exe ./src
      shell: pwsh

    - name: Install Inno Setup
      run: choco install innosetup
      shell: pwsh

    - name: List directory contents
      run: dir
      shell: cmd

    - name: Create Windows installer
      run: iscc src/install/windows/installer.iss
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output-windows
        path: |
          dashball.exe
          Output/*.exe
